spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vacationdb
    username: user
    password: user_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true